### ISSUE TITLE
Problems with dependencies

### ISSUE THREAD

**Issue by talgautb** [frontendbabel/frontendbabel.github.com#105]
is it real to update npm packages ?)

`current: {"node":"0.12.7","npm":"2.13.2"}`

**Comment by varya** [comment]
Got the same error. Do you know which packages needed to be updated?

**Comment by varya** [comment]
Updated docpad plugins. It still gets some errors when running, but the website works https://github.com/frontendbabel/frontendbabel.github.com/pull/106

**Comment by talgautb** [comment]
some problems with node, for example `engine puml-link@0.0.1: wanted: {"node":"0.10"}`

**Comment by varya** [comment]
Do you have docpad globally installed?

I run from scratch again, it works. My environment:
```
varyas-mbp £ ~/ ⤳ features/extend-in-less
  › node -v
v0.12.7
varyas-mbp £ ~/ ⤳ features/extend-in-less
  › npm -v
2.13.2
varyas-mbp £ ~/ ⤳ features/extend-in-less
  › docpad -V
v6.78.1 (global installation: /Users/varya/.nvm/versions/node/v0.12.7/lib/node_modules/docpad)
```

**Comment by varya** [comment]
I also got this WARN

```
npm WARN engine puml-link@0.0.1: wanted: {"node":"0.10"} (current: {"node":"0.12.7","npm":"2.13.2"})
npm WARN prefer global bower@1.4.1 should be installed with -g
```

But it's only a warning, not an error. The `docpad run` works after that.

**Comment by varya** [comment]
Did it finally worked for you?

**Comment by talgautb** [comment]
yep, the same warnings, but it work,
`bower install` helped :)

**Comment by MunGell** [comment]
Do you think we need a Makefile for installation process, so it will `npm install`, `bower install` and anything else with only one command?
