### ISSUE TITLE
Translate: Стилизуем placeholder при помощи CSS

### ISSUE THREAD

**Issue by varya** [frontendbabel/frontendbabel.github.com#38]
http://html5.by/blog/placeholder/

**Comment by talgautb** [comment]
@varya еще актуально ?

**Comment by varya** [comment]
Привет. Да!

**Comment by talgautb** [comment]
Начал переводить, уведомляю, чтобы не было дубликатов :)
можно назначить на меня тикет

**Comment by varya** [comment]
Спасибо! Когда будешь делать PR, напиши там в title кроме самого текста ещё и "Fix #38" — этот таск сам закроется.

**Comment by talgautb** [comment]
Статья написана :) но не могу запустить #105
